# Generated by Django 3.2.4 on 2021-06-14 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(choices=[(1, 'きゅうあん'), (2, 'こうしえん')], default=None, verbose_name='出勤場所名')),
                ('in_out', models.IntegerField(choices=[(1, 'IN'), (0, 'OUT')], default=None, verbose_name='IN/OUT')),
                ('time', models.TimeField(verbose_name='打刻時間')),
                ('date', models.DateField(verbose_name='打刻日')),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='従業員')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
